#!/usr/bin/env python3
"""Generate INDEX.md — a readonly grouped view of all decks.

Reads every TSV at the repo root and writes INDEX.md grouping entries by
deck and then by tag. Source TSV files are not modified.

Usage:
  python scripts/index.py
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

from common import REPO_ROOT, deck_paths, parse_tsv, stderr

INDEX_PATH = REPO_ROOT / "INDEX.md"

DECK_TITLES = {
    "Chinese_Core_Conversation.tsv": "Core Conversation",
    "Chinese_Idioms_Proverbs_Classical.tsv": "Idioms / Proverbs / Classical",
    "Chinese_Slang_Dialect_Flavor.tsv": "Slang / Dialect / Flavor",
}


def main() -> int:
    paths = deck_paths()
    if not paths:
        stderr("no TSV files found")
        return 1

    out: list[str] = []
    out.append("# Deck Index")
    out.append("")
    out.append(
        "_Auto-generated by `scripts/index.py`. Do not edit by hand — "
        "regenerate after appending new rows._"
    )
    out.append("")

    total = 0
    for path in paths:
        try:
            _, rows = parse_tsv(path)
        except ValueError as e:
            stderr(f"skipping {path.name}: {e}")
            continue
        total += len(rows)

        title = DECK_TITLES.get(path.name, path.stem)
        out.append(f"## {title}")
        out.append(f"_{len(rows)} entries — `{path.name}`_")
        out.append("")

        by_tag: dict[str, list] = defaultdict(list)
        untagged = []
        for r in rows:
            if not r.tags:
                untagged.append(r)
                continue
            for t in r.tags:
                by_tag[t].append(r)

        for tag in sorted(by_tag, key=lambda t: (t, len(by_tag[t]))):
            out.append(f"### `{tag}` ({len(by_tag[tag])})")
            out.append("")
            for r in sorted(by_tag[tag], key=lambda r: r.line_no):
                english = r.english.replace("|", "\\|")
                out.append(f"- **{r.hanzi}** ({r.pinyin}) — {english}")
            out.append("")

        if untagged:
            out.append(f"### _untagged_ ({len(untagged)})")
            out.append("")
            for r in untagged:
                english = r.english.replace("|", "\\|")
                out.append(f"- **{r.hanzi}** ({r.pinyin}) — {english}")
            out.append("")

    out.insert(3, f"_{total} total entries across {len(paths)} decks._")
    out.insert(4, "")

    INDEX_PATH.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {INDEX_PATH.relative_to(REPO_ROOT)} ({total} entries).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
